[package]
name = "bconv"
version = "0.1.0"
edition = "2024"

[dependencies]
banker = { path = "../banker" }
clap = { version = "4.5.49", features = ["derive"] }
colog = "1.4.0"
log = "0.4.28"
strum = "0.27.2"
strum_macros = "0.27.2"
thiserror-context = "0.1.2"
