[package]
name = "banker"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1"
log = "0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
thiserror-context = "0"
